### ISSUE TITLE
Problems with simple/form_declarative.py

### ISSUE THREAD

**Issue by ralphtheninja** [ptahproject/examples#12]
magnus@magnus-MS-7350VP ~/env/examples/simple $ ../../bin/python form_declarative.py 
Traceback (most recent call last):
  File "form_declarative.py", line 3, in <module>
    from pyramid.view import view_config
  File "/home/magnus/env/local/lib/python2.7/site-packages/pyramid-1.3a5-py2.7.egg/pyramid/**init**.py", line 1, in <module>
    from pyramid.request import Request
  File "/home/magnus/env/local/lib/python2.7/site-packages/pyramid-1.3a5-py2.7.egg/pyramid/request.py", line 3, in <module>
    from zope.deprecation import deprecate
ImportError: No module named deprecation

**Comment by fafhrd91** [comment]
just tested with ptah-0.3.0, all 3 examples work fine.

did you install ptah into virtualenv?

**Comment by ralphtheninja** [comment]
I installed ptah-0.3.0 myself, but perhaps I forgot to reinstall the
examples-repository. Is that needed?

2012/1/13 Nikolay Kim <
reply@reply.github.com

**Comment by fafhrd91** [comment]
thats very strange. try to install zope.deprecation manually

  $ pip install zope.deprecation

**Comment by ralphtheninja** [comment]
Will take a few days since I'm away from home, but I'll get back to you.
Thanks!

2012/1/13 Nikolay Kim <
reply@reply.github.com

**Comment by ralphtheninja** [comment]
Hmm nope, that doesn't cut it either =/

2012/1/13 Magnus Skog lars.magnus.skog@gmail.com

**Comment by fafhrd91** [comment]
could you try with fresh virtualenv
